series: GLFW Graphics
title: Multi-Object Single-Buffer
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program serves to demonstrate how to use multiple objects in a single buffer.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Marching Cubes Tutorial
